README.md
package-lock.json
package.json
src/conductor.ts

Updates for changes in conductor api re app_id -> installed_app_id
confirmed working for holochain rev: 2dfe85db10a

update for conductor-api dev-12

---

README.md

This worked for me with holochain commit 8fa617e0d4adfa0f1002d3944d2c57bb009667f1.
@Connoropolous @zippy @maackle

Fix documentation on custom DNA properties

---

Cargo.lock
README.md
ci_scripts/install-holochain.sh
test/e2e/fixture/zomes/test/Cargo.toml

This is what's causing all the other PRs' builds to fail

Bump holochain due to retro-active breaking change

---

example/test.ts
src/conductor.ts
src/types.ts
test/common.ts
test/e2e/test-always-on.ts
test/e2e/test-remote.ts

- adds optional `installed-app-id` to Type `installAgentsHapp`

add installed_app_id option in installAgentsHapp

---

package.json
src/util.ts

Axios would have to be updated for security reasons. I see that it's only used in a deprecated function to download DNA files. I don't know why Tryorama needed such a function. Can we remove it and remove the Axios package too?

Remove axios

---

CHANGELOG.md
Cargo.lock
README.md
crates/trycp_server/Cargo.toml
default.nix
nix/sources.json
package-lock.json
package.json
ts/test/fixture/dna.yaml
ts/test/fixture/zomes/entry/Cargo.toml
ts/test/fixture/zomes/entry/src/lib.rs
ts/test/local/conductor.ts
ts/test/trycp/conductor.ts

- Holochain: Upgrade Holochain & @holochain/client & replace Element/Header with Action/Record

feat(hc)!: upgrade hc & hc-client & rename header/element

---

Cargo.lock
crates/trycp_server/Cargo.lock

The lock files seemed like it was not updated and was not able to build in holo-nixpkgs

updated lock files

---

CHANGELOG.md
package-lock.json
package.json

build(js-client): upgrade to v0.12.0

---

README.md
flake.lock
flake.nix
ts/src/types.ts
ts/test/local/scenario.ts

Examples in readme get easily outdated or are inaccurate as they're not tested. Link to specific examples of test suite instead.
closes #185

docs(readme): link to tested examples

---

CHANGELOG.md
package-lock.json
package.json
ts/src/local/conductor.ts
ts/test/local/scenario.ts

Restore zome call by role name instead of cell id

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
crates/trycp_server/Cargo.toml
flake.lock
package-lock.json
package.json
ts/src/trycp/conductor/conductor.ts
ts/src/trycp/trycp-client.ts
ts/src/trycp/types.ts
ts/test/fixture/zomes/integrity/Cargo.toml
ts/test/local/conductor.ts
ts/test/trycp/client.ts
ts/test/trycp/conductor.ts

completes and closes https://github.com/holochain/holochain/issues/3598

fix(serialization)!: match conductor api updates

---

flake.lock
package-lock.json
package.json
ts/test/fixture/zomes/coordinator/src/lib.rs
ts/test/fixture/zomes/integrity/src/lib.rs
ts/test/local/conductor.ts
ts/test/local/scenario.ts
ts/test/trycp/conductor.ts

This won't work until we have the updated client available

Test system signals

---

docs/tryorama.appoptions.md
docs/tryorama.appoptions.signalhandler.md
docs/tryorama.clientsplayersoptions.md
docs/tryorama.clientsplayersoptions.signalhandler.md
docs/tryorama.getcallablecell.md
docs/tryorama.trycpclient.setsignalhandler.md
docs/tryorama.trycpconductor.on.md
ts/src/local/conductor.ts
ts/src/trycp/conductor/conductor.ts
ts/src/trycp/conductor/scenario.ts
ts/src/trycp/trycp-client.ts
ts/src/trycp/util.ts
ts/src/types.ts
ts/test/fixture/zomes/coordinator/src/lib.rs
ts/test/local/conductor.ts
ts/test/local/scenario.ts
ts/test/trycp/conductor.ts
ts/test/trycp/scenario.ts

- updates signal references to be compatible with changes from [holochain-client-js pr # 268](https://github.com/holochain/holochain-client-js/pull/268)

signal update fixes

---

CHANGELOG.md
package-lock.json
package.json

Not published to npm yet but will do if approved here.

chore(release): v0.18.0-dev.3

---

.github/workflows/test.yml
CHANGELOG.md
Cargo.lock
flake.lock
package-lock.json
ts/src/local/conductor.ts

fix(local): local conductor startup phrase parsing

---

.github/pull_request_template.md
CHANGELOG.md
flake.lock
package-lock.json
package.json
ts/test/local/conductor.ts
ts/test/trycp/conductor.ts

Bump js-client 0.19.0-dev.8

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.18.0-rc.0

---

CHANGELOG.md
package-lock.json
package.json

fix: Move `js-yaml` to dependencies

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.18.0-rc.1

---

CHANGELOG.md
ts/src/conductor-helpers.ts

fix: log missing bootstarp srv

---

CHANGELOG.md
Cargo.lock
Cargo.toml
package-lock.json
package.json

chore(release): v0.18.0

---

.github/workflows/test.yml

chore: Add ci_pass check

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.18.2
